name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Analysing the code with pylint
      run: |
        black $(git ls-files '*.py')
        pylint $(git ls-files '*.py')
