name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Analysing the code with pylint
      run: |
        pylint tests/flag_attn/test_piecewise_attention.py
